#######################################
#                                     #
#           H A R D C O R E +         #
#              V1.4-Alpha             #
#              By:Seauxz              #
#                                     #
#######################################


action-on-death: "spectate" # can be either "ban" or "spectate"

ban-length: 1 # in hours, 0 means permanent ban

ban-message-enabled: true # set to false to disable ban message
ban-message: "You died!" # message displayed to the player when they get banned

ban-permissions: "hardcore.death.banimmune" # permission node to be immune from banning

spectate-permissions: "hardcore.death.spectateimmune" # permission node to be immune from spectating

ban-after-deaths-enabled: true # set to false to disable ban after deaths
ban-after-deaths: 1 # number of deaths before the player gets banned

place-head-on-death: true # set it to "false" will disable player heads

# If set to true, players can only lose lives by being killed by other players.
# If false, deaths from all causes will result in loss of life.
lose-lives-only-by-players: false

spawn-thunder-on-death: true # Enable or disable spawning of thunder at the location of death.

steal-lives: false # Enable or disable the ability for players to steal lives by killing.
max-lives: 10 # Maximum number of lives a player can have.

# List of worlds in which the plugin will be active.
# Edit or/and add according to the names of your own worlds.
worlds:
  world: true
  world_nether: true
  world_the_end: true

