name: Hardcore
main: death.hardcore.Hardcore
version: 1.0
author: Seauxz
commands:
  revive:
    description: Revives a player from spectator mode or unbans them.
    usage: /<command> <player>
permissions:
  hardcore.revive:
    description: Allows use of the revive command
    default: op
