name: Hardcore
main: death.hardcore.Hardcore
version: 1.3.0
author: Seauxz
api-version: 1.16

commands:
  revive:
    description: Revives a player from spectator mode or unbans them.
    usage: /<command> <player>
  hardcore:
    description: Reloads the configuration
    usage: /<command> reload
    permission: hardcore.reload
  lives:
    description: Displays the number of lives a player has left.
    usage: /<command>

permissions:
  hardcore.revive:
    description: Allows use of the revive command
    default: op
  hardcore.reload:
    description: Allows use of the hardcore reload command
    default: op
  hardcore.lives:
    description: Allows use of the lives command
    default: true
