name: Hardcore
main: death.hardcore.Hardcore
version: 1.2
author: Seauxz
api-version: 1.19

commands:
  revive:
    description: Revives a player from spectator mode or unbans them.
    usage: /<command> <player>
  hardcore:
    description: Reloads the configuration
    usage: /<command> reload
    permission: hardcore.reload

permissions:
  hardcore.revive:
    description: Allows use of the revive command
    default: op
  hardcore.reload:
    description: Allows use of the hardcore reload command
    default: op