name: Hardcore
main: death.hardcore.Hardcore
version: 1.4.0-Beta
author: Seauxz
api-version: 1.16

commands:
  revive:
    description: Revives a player from spectator mode or unbans them.
    usage: /<command> <player>
  hardcore:
    description: Reloads the configuration
    usage: /<command> reload
    permission: hardcore.reload
  lives:
    description: Displays the number of lives a player has left.
    usage: /<command>
  givelife:
    description: Gives a life to a player.
    usage: /<command> <player>
    permission: hardcore.givelife
  removelife:
    description: Removes lives from a player.
    usage: /<command> <player>
    permission: hardcore.removelife
  clearheads:
    description: Clear all player heads
    usage: /<command>
    permission: hardcore.clearheads

permissions:
  hardcore.revive:
    description: Allows use of the revive command
    default: op
  hardcore.reload:
    description: Allows use of the hardcore reload command
    default: op
  hardcore.lives:
    description: Allows use of the lives command
    default: true
  hardcore.givelife:
    description: Allows use of the givelife command
    default: op
  hardcore.removelife:
    description: Removes lives from a player.
    default: op
  hardcore.clearheads:
    description: Allows use of the clearheads command
    default: op
